2024-01-07 18:17:15,386 ERROR 1894 [-/127.0.0.1/-/1ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
    --------------------
    at Protocol._enqueue (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:48:16)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at Pool.getConnection (node:internal/util:428:12)
    at Pool.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:202:8)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 1894
hostname: xuhailongdeMacBook-Pro.local

2024-01-07 18:19:13,098 ERROR 2051 [-/127.0.0.1/-/1ms GET /] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at Handshake.emit (node:events:514:28)
    at Handshake._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Sequence.js:124:8)
    at Timer._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Timer.js:32:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
    --------------------
    at Protocol._enqueue (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:48:16)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at Pool.getConnection (node:internal/util:428:12)
    at Pool.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:202:8)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    sql: select now() as currentTime;
code: "PROTOCOL_SEQUENCE_TIMEOUT"
fatal: true
timeout: 10000
name: "PROTOCOL_SEQUENCE_TIMEOUTError"
pid: 2051
hostname: xuhailongdeMacBook-Pro.local

2024-01-07 19:06:45,868 ERROR 4207 [-/127.0.0.1/-/62ms POST /register?username=123123123] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'mysql.users' doesn't exist
    at Sequence._packetToError (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    --------------------
    at Pool.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:428:12)
    at RDSClient._query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/operator.js:62:31)
    at HomeController.register (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:13:23)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    sql: SELECT users FROM mysql.users;
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'mysql.users' doesn't exist"
sqlState: "42S02"
index: 0
sql: "SELECT users FROM mysql.users;"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 4207
hostname: xuhailongdeMacBook-Pro.local

2024-01-07 19:25:13,997 ERROR 4911 [-/127.0.0.1/-/151ms POST /register?username=text&password=text] nodejs.unhandledRejectionError: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value
    at Sequence._packetToError (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    --------------------
    at Pool.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:428:12)
    at RDSClient._query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/operator.js:62:31)
    at HomeController.register (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:16:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    sql: INSERT INTO users (username, password) VALUES ('test', 'test');
code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlMessage: "Field 'id' doesn't have a default value"
sqlState: "HY000"
index: 0
sql: "INSERT INTO users (username, password) VALUES ('test', 'test');"
name: "unhandledRejectionError"
pid: 4911
hostname: xuhailongdeMacBook-Pro.local

2024-01-07 19:25:56,083 ERROR 4948 [-/127.0.0.1/-/88ms POST /register?username=text&password=text] nodejs.unhandledRejectionError: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value
    at Sequence._packetToError (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    --------------------
    at Pool.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:428:12)
    at RDSClient._query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/operator.js:62:31)
    at HomeController.register (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:16:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    sql: INSERT INTO users (username, password) VALUES ('test', 'test');
code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlMessage: "Field 'id' doesn't have a default value"
sqlState: "HY000"
index: 0
sql: "INSERT INTO users (username, password) VALUES ('test', 'test');"
name: "unhandledRejectionError"
pid: 4948
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 17:20:54,027 ERROR 7447 [-/127.0.0.1/-/18ms POST /login] nodejs.ReferenceError: token is not defined
    at HomeController.login (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:54:7)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:45:18)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 7447
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 17:56:03,943 ERROR 9716 [-/127.0.0.1/-/3ms GET /verifyToken?token=eyJhbGciOiJIUzI1NfdsafsadiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTYiLCJ1c2VybmFtZSI6ImV4YW1wbGVVc2VyIiwiaWF0IjoxNzA1ODMwNjc2LCJleHAiOjE3MDU4MzQyNzZ9.QJ2scGS-mPvB0co7oQ2OpQpNSl3Q6tRElQvPOpwukQM] nodejs.JsonWebTokenError: invalid token
    at module.exports [as verify] (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/jsonwebtoken/verify.js:82:17)
    at HomeController.verifyToken (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:60:33)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:45:18)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
name: "JsonWebTokenError"
message: "invalid token"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 9716
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 17:56:12,369 ERROR 9716 [-/127.0.0.1/-/1ms GET /verifyToken?token=eyJhbGciOiJIUzI1NfdsafsadiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTYiLCJ1c2VybmFtZSI6ImV4YW1wbGVVc2VyIiwiaWF0IjoxNzA1ODMwNjc2LCJleHAiOjE3MDU4MzQyNzZ9.QJ2scGS-mPvB0co7oQ2OpQpNSl3Q6tRElQvPOpwukQM] nodejs.JsonWebTokenError: invalid token
    at module.exports [as verify] (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/jsonwebtoken/verify.js:82:17)
    at HomeController.verifyToken (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:60:33)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:45:18)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
name: "JsonWebTokenError"
message: "invalid token"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 9716
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 17:56:12,994 ERROR 9716 [-/127.0.0.1/-/0ms GET /verifyToken?token=eyJhbGciOiJIUzI1NfdsafsadiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTYiLCJ1c2VybmFtZSI6ImV4YW1wbGVVc2VyIiwiaWF0IjoxNzA1ODMwNjc2LCJleHAiOjE3MDU4MzQyNzZ9.QJ2scGS-mPvB0co7oQ2OpQpNSl3Q6tRElQvPOpwukQM] nodejs.JsonWebTokenError: invalid token
    at module.exports [as verify] (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/jsonwebtoken/verify.js:82:17)
    at HomeController.verifyToken (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:60:33)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:45:18)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
name: "JsonWebTokenError"
message: "invalid token"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 9716
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 17:56:13,160 ERROR 9716 [-/127.0.0.1/-/1ms GET /verifyToken?token=eyJhbGciOiJIUzI1NfdsafsadiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTYiLCJ1c2VybmFtZSI6ImV4YW1wbGVVc2VyIiwiaWF0IjoxNzA1ODMwNjc2LCJleHAiOjE3MDU4MzQyNzZ9.QJ2scGS-mPvB0co7oQ2OpQpNSl3Q6tRElQvPOpwukQM] nodejs.JsonWebTokenError: invalid token
    at module.exports [as verify] (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/jsonwebtoken/verify.js:82:17)
    at HomeController.verifyToken (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:60:33)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:45:18)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
name: "JsonWebTokenError"
message: "invalid token"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 9716
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 17:56:13,362 ERROR 9716 [-/127.0.0.1/-/1ms GET /verifyToken?token=eyJhbGciOiJIUzI1NfdsafsadiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTYiLCJ1c2VybmFtZSI6ImV4YW1wbGVVc2VyIiwiaWF0IjoxNzA1ODMwNjc2LCJleHAiOjE3MDU4MzQyNzZ9.QJ2scGS-mPvB0co7oQ2OpQpNSl3Q6tRElQvPOpwukQM] nodejs.JsonWebTokenError: invalid token
    at module.exports [as verify] (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/jsonwebtoken/verify.js:82:17)
    at HomeController.verifyToken (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:60:33)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:45:18)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
name: "JsonWebTokenError"
message: "invalid token"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 9716
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 17:58:06,720 ERROR 9811 [-/127.0.0.1/-/6ms GET /verifyToken?token=eyJhbGciOiJIUzI1NfdsafsadiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTYiLCJ1c2VybmFtZSI6ImV4YW1wbGVVc2VyIiwiaWF0IjoxNzA1ODMwNjc2LCJleHAiOjE3MDU4MzQyNzZ9.QJ2scGS-mPvB0co7oQ2OpQpNSl3Q6tRElQvPOpwukQM] nodejs.ReferenceError: decoded is not defined
    at HomeController.verifyToken (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:60:29)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:45:18)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 9811
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 18:23:51,051 ERROR 4533 nodejs.ClusterClientNoResponseError: client no response in 356974ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 4533
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 19:57:27,926 ERROR 4533 nodejs.ClusterClientNoResponseError: client no response in 1399274ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 4533
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 20:17:06,869 ERROR 4533 nodejs.ClusterClientNoResponseError: client no response in 1053848ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 4533
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 20:36:56,883 ERROR 4533 nodejs.ClusterClientNoResponseError: client no response in 1009969ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 4533
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 20:56:51,875 ERROR 4533 nodejs.ClusterClientNoResponseError: client no response in 1074979ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 4533
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 21:16:41,889 ERROR 4533 nodejs.ClusterClientNoResponseError: client no response in 1069971ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 4533
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 21:34:13,815 ERROR 4533 nodejs.ClusterClientNoResponseError: client no response in 857102ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 4533
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 21:40:45,133 ERROR 4533 nodejs.ClusterClientNoResponseError: client no response in 271369ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 4533
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 21:53:04,370 ERROR 4533 nodejs.ClusterClientNoResponseError: client no response in 699221ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 4533
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 22:10:52,703 ERROR 4533 nodejs.ClusterClientNoResponseError: client no response in 1028339ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 4533
hostname: xuhailongdeMacBook-Pro.local

2024-01-21 22:18:30,579 ERROR 4533 nodejs.ClusterClientNoResponseError: client no response in 337908ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 4533
hostname: xuhailongdeMacBook-Pro.local

2024-03-03 23:04:30,632 ERROR 5006 nodejs.ClusterClientNoResponseError: client no response in 981355ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 5006
hostname: xuhailongdeMacBook-Pro.local

2024-03-03 23:06:26,652 ERROR 5006 nodejs.ClusterClientNoResponseError: client no response in 115956ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 5006
hostname: xuhailongdeMacBook-Pro.local

2024-03-23 18:17:10,608 ERROR 3682 [-/127.0.0.1/-/22ms GET /wxLogin?param=%7B%22code%22%3A%220e3wlz0w3kYOs23SlX2w3rLkGJ3wlz0w%22%7D] nodejs.TypeError: ctx.body is not a function
    at HomeController.wxLogin (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:79:9)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:45:18)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 3682
hostname: xuhailongdeMacBook-Pro.local

2024-03-23 18:17:48,379 ERROR 3737 [-/127.0.0.1/-/15ms GET /wxLogin?param=%7B%22code%22%3A%220d3Tnz0w3d0Ps234GL1w326V4m1Tnz0S%22%7D] nodejs.TypeError: ctx.body is not a function
    at HomeController.wxLogin (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:79:9)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:45:18)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 3737
hostname: xuhailongdeMacBook-Pro.local

2024-03-23 18:18:15,293 ERROR 3762 [-/127.0.0.1/-/17ms GET /wxLogin?param=%7B%22code%22%3A%220f3KEW1w3bTZr23naR0w3Rkzb90KEW16%22%7D] nodejs.TypeError: ctx.body is not a function
    at HomeController.wxLogin (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:79:9)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:45:18)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 3762
hostname: xuhailongdeMacBook-Pro.local

2024-03-23 18:19:00,259 ERROR 3762 [-/127.0.0.1/-/2ms GET /wxLogin?param=%7B%22code%22%3A%220c3SyD000sPvNR1Cax000n17w52SyD0b%22%7D] nodejs.TypeError: ctx.body is not a function
    at HomeController.wxLogin (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:79:9)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:45:18)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 3762
hostname: xuhailongdeMacBook-Pro.local

2024-03-23 18:19:07,033 ERROR 3762 [-/127.0.0.1/-/1ms GET /wxLogin?code=0d3WBo1w3l5ys23hQl1w3F7nu81WBo1O] nodejs.TypeError: ctx.body is not a function
    at HomeController.wxLogin (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:79:9)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:45:18)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 3762
hostname: xuhailongdeMacBook-Pro.local

2024-03-30 12:52:41,111 ERROR 2991 [-/127.0.0.1/-/1ms GET /] nodejs.ER_BAD_DB_ERRORError: ER_BAD_DB_ERROR: Unknown database 'space-eaas'
    at Sequence._packetToError (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    --------------------
    at Protocol._enqueue (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:48:16)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at Pool.getConnection (node:internal/util:428:12)
    at Pool.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:202:8)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    sql: select now() as currentTime;
code: "ER_BAD_DB_ERROR"
errno: 1049
sqlMessage: "Unknown database 'space-eaas'"
sqlState: "42000"
fatal: true
name: "ER_BAD_DB_ERRORError"
pid: 2991
hostname: xuhailongdeMacBook-Pro.local

2024-03-30 12:52:50,961 ERROR 3043 [-/127.0.0.1/-/1ms GET /] nodejs.ER_BAD_DB_ERRORError: ER_BAD_DB_ERROR: Unknown database 'space-eaas'
    at Sequence._packetToError (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    --------------------
    at Protocol._enqueue (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:48:16)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at Pool.getConnection (node:internal/util:428:12)
    at Pool.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:202:8)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    sql: select now() as currentTime;
code: "ER_BAD_DB_ERROR"
errno: 1049
sqlMessage: "Unknown database 'space-eaas'"
sqlState: "42000"
fatal: true
name: "ER_BAD_DB_ERRORError"
pid: 3043
hostname: xuhailongdeMacBook-Pro.local

2024-03-30 15:45:20,169 ERROR 8600 [-/192.168.31.226/-/312ms GET /wxLogin?code=0a3I73100GwsPR1nGN000yHteY0I731d] nodejs.unhandledRejectionError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '==)' at line 1
    at Sequence._packetToError (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    --------------------
    at Pool.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:428:12)
    at RDSClient._query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/operator.js:62:31)
    at HomeController.wxLogin (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:100:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    sql: insert into user(nickname, openid, session_key) values('微信用户', oPhkS40wMy5ikDWpMaxN8VHxz2KM, wc+DmgPtUOt2gSc8APt9cA==)
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '==)' at line 1"
sqlState: "42000"
index: 0
sql: "insert into user(nickname, openid, session_key) values('微信用户', oPhkS40wMy5ikDWpMaxN8VHxz2KM, wc+DmgPtUOt2gSc8APt9cA==)"
name: "unhandledRejectionError"
pid: 8600
hostname: xuhailongdeMacBook-Pro.local

2024-03-30 15:46:15,519 ERROR 8645 [-/192.168.31.226/-/699ms GET /wxLogin?code=0f365v000Py0QR1yTo000SQ9Lh465v0k] nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column 'session_key' in 'field list'
    at Sequence._packetToError (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    --------------------
    at Pool.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:428:12)
    at RDSClient._query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/operator.js:62:31)
    at HomeController.wxLogin (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:100:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    sql: insert into user(nickname, openid, session_key) values('微信用户', 'oPhkS40wMy5ikDWpMaxN8VHxz2KM', 'wc+DmgPtUOt2gSc8APt9cA==')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'session_key' in 'field list'"
sqlState: "42S22"
index: 0
sql: "insert into user(nickname, openid, session_key) values('微信用户', 'oPhkS40wMy5ikDWpMaxN8VHxz2KM', 'wc+DmgPtUOt2gSc8APt9cA==')"
name: "unhandledRejectionError"
pid: 8645
hostname: xuhailongdeMacBook-Pro.local

2024-03-30 15:46:53,586 ERROR 8645 [-/192.168.31.226/-/233ms GET /wxLogin?code=0a33qOFa1C8HaH0nONHa1p8vLL03qOFu] nodejs.unhandledRejectionError: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value
    at Sequence._packetToError (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    --------------------
    at Pool.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:428:12)
    at RDSClient._query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/operator.js:62:31)
    at HomeController.wxLogin (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:100:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    sql: insert into user(nickname, openid, session_key) values('微信用户', 'oPhkS40wMy5ikDWpMaxN8VHxz2KM', 'wc+DmgPtUOt2gSc8APt9cA==')
code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlMessage: "Field 'id' doesn't have a default value"
sqlState: "HY000"
index: 0
sql: "insert into user(nickname, openid, session_key) values('微信用户', 'oPhkS40wMy5ikDWpMaxN8VHxz2KM', 'wc+DmgPtUOt2gSc8APt9cA==')"
name: "unhandledRejectionError"
pid: 8645
hostname: xuhailongdeMacBook-Pro.local

2024-03-30 15:48:18,409 ERROR 8645 [-/192.168.31.226/-/261ms GET /wxLogin?code=0f3UfM000SRJPR1L4L1000wIpW1UfM0R] nodejs.unhandledRejectionError: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value
    at Sequence._packetToError (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    --------------------
    at Pool.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:428:12)
    at RDSClient._query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/ali-rds/lib/operator.js:62:31)
    at HomeController.wxLogin (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/login.js:100:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    sql: insert into user(nickname, openid, session_key) values('微信用户', 'oPhkS40wMy5ikDWpMaxN8VHxz2KM', 'wc+DmgPtUOt2gSc8APt9cA==')
code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlMessage: "Field 'id' doesn't have a default value"
sqlState: "HY000"
index: 0
sql: "insert into user(nickname, openid, session_key) values('微信用户', 'oPhkS40wMy5ikDWpMaxN8VHxz2KM', 'wc+DmgPtUOt2gSc8APt9cA==')"
name: "unhandledRejectionError"
pid: 8645
hostname: xuhailongdeMacBook-Pro.local

2024-03-30 18:39:57,905 ERROR 14251 [-/192.168.31.226/-/20ms POST /wx/user/setting] nodejs.ReferenceError: paramsToSql is not defined
    at HomeController.setUser (/Users/xuhailong/Desktop/item-web/space-eaas/app/controller/user.js:33:21)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:45:18)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/@eggjs/router/lib/router.js:186:18
    at dispatch (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:44:32)
    at /Users/xuhailong/Desktop/item-web/space-eaas/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 14251
hostname: xuhailongdeMacBook-Pro.local

2024-03-30 21:59:11,220 ERROR 5853 nodejs.ClusterClientNoResponseError: client no response in 626944ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 5853
hostname: xuhailongdeMacBook-Pro.local

2024-03-30 22:19:28,470 ERROR 5853 nodejs.ClusterClientNoResponseError: client no response in 1079715ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 5853
hostname: xuhailongdeMacBook-Pro.local

2024-03-30 22:27:57,826 ERROR 5853 nodejs.ClusterClientNoResponseError: client no response in 389268ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xuhailong/Desktop/item-web/space-eaas/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
name: "ClusterClientNoResponseError"
pid: 5853
hostname: xuhailongdeMacBook-Pro.local

